version: '3.8'

services:
  reels-ui:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mount data directory for persistent SQLite database
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/debug"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
