name: Docker Build & Deploy

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: {}

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  setup-buildx:
    runs-on: ubuntu-latest
    outputs:
      builder: ${{ steps.builder.outputs.name }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

  build-and-push:
    needs: setup-buildx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Remote deploy via SSH (optional)
        if: env.SSH_HOST != '' && env.SSH_USER != '' && secrets.SSH_PRIVATE_KEY
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull $IMAGE_NAME:latest || true
            docker stop reels-ui || true
            docker rm reels-ui || true
            docker run -d --restart always --name reels-ui -p 3000:3000 $IMAGE_NAME:latest
